
import type { Review } from '@/types/review';

export const reviews: Review[] = [
  {
    id: '1',
    name: 'Sarah L.',
    company: 'EcoFriendly Goods',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman portrait',
    rating: 5,
    quote: 'Gorilla Tech Solutions completely transformed our online presence. Their SEO strategy was a game-changer, tripling our organic traffic in just six months. We couldn\'t be happier with the results!',
    pinned: true,
  },
  {
    id: '2',
    name: 'Mark C.',
    company: 'Innovate SaaS',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'man portrait',
    rating: 5,
    quote: 'The PPC team is phenomenal. They slashed our cost-per-acquisition by 40% while improving lead quality. Their data-driven approach is second to none. Highly recommended for any B2B company.',
    pinned: true,
  },
  {
    id: '3',
    name: 'Jessica P.',
    company: 'The Local Cafe',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman smiling',
    rating: 5,
    quote: 'We were struggling with social media until we partnered with them. They built a vibrant community around our brand and drove a noticeable increase in foot traffic. It feels like they\'re part of our team.',
    pinned: false,
  },
  {
    id: '4',
    name: 'David R.',
    company: 'DR Financial',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'man professional',
    rating: 5,
    quote: 'Their content marketing and lead generation strategies delivered high-quality leads consistently. The ROI from their LinkedIn campaign was impressive. Professional, responsive, and effective.',
    pinned: false,
  },
  {
    id: '5',
    name: 'Emily T.',
    company: 'La Boutique',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman fashion',
    rating: 4,
    quote: 'The team helped us launch our new collection with a fantastic influencer marketing campaign. The buzz they created was incredible and directly translated to a significant increase in online sales.',
    pinned: false,
  },
  {
    id: '6',
    name: 'Michael B.',
    company: 'Prime Properties',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'man realtor',
    rating: 5,
    quote: 'Thanks to their local SEO expertise, our agency now dominates the search rankings in our city. We\'ve seen a steady stream of qualified inquiries since they optimized our website and GMB profile.',
    pinned: false,
  },
  {
    id: '7',
    name: 'Alex Johnson',
    company: 'Tech Solutions Inc.',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'man tech',
    rating: 5,
    quote: 'An absolutely outstanding experience. The team is professional, knowledgeable, and delivered results that far exceeded our expectations. Their SEO work put us on the map!',
    pinned: true,
  },
  {
    id: '8',
    name: 'Samantha Lee',
    company: 'Creative Designs Co.',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman designer',
    rating: 5,
    quote: 'The social media campaigns they ran for us were creative, engaging, and drove a huge amount of traffic to our site. I\'m thrilled with the outcome and the team\'s dedication.',
    pinned: false,
  },
  {
    id: '9',
    name: 'Tom Wilson',
    company: 'Global Exports',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'man business',
    rating: 5,
    quote: 'We needed a complete digital marketing overhaul, and Gorilla Tech Solutions delivered. Their strategic approach to content and PPC has been instrumental in our growth this year.',
    pinned: true,
  },
  {
    id: '10',
    name: 'Linda Garcia',
    company: 'Healthy Eats',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman chef',
    rating: 4,
    quote: 'Their email marketing automation has saved us so much time and has been incredibly effective at nurturing leads. We\'ve seen a definite increase in repeat customers.',
    pinned: false,
  },
  {
    id: '11',
    name: 'Kevin Harris',
    company: 'FitHub',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'man fitness',
    rating: 5,
    quote: 'The best in the business! Their integrated marketing campaign for our app launch was a massive success, leading to 50,000+ downloads in the first month. Highly strategic and flawless execution.',
    pinned: true,
  },
  {
    id: '12',
    name: 'Rachel Adams',
    company: 'Sunset Travel',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman travel',
    rating: 5,
    quote: 'Our bookings have soared since they revamped our content strategy. The travel guides they created are not only beautiful but also rank highly on Google. A pleasure to work with!',
    pinned: false,
  },
  {
    id: '13',
    name: 'Chris Martinez',
    company: 'AutoRevive',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'man mechanic',
    rating: 5,
    quote: 'They optimized our PPC campaigns for our dealership network and the results were almost immediate. Lead volume is up by 50% and we\'re spending less. That\'s a win-win.',
    pinned: false,
  },
  {
    id: '14',
    name: 'Megan Chen',
    company: 'FutureLearn',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman student',
    rating: 5,
    quote: 'The team managed our Google Ads for student enrollment, and they did a fantastic job. Our cost per acquisition is down 30%, and our enrollment numbers are at an all-time high.',
    pinned: false,
  },
  {
    id: '15',
    name: 'George Wright',
    company: 'Wright & Co. Law',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'man lawyer',
    rating: 5,
    quote: 'Building authority in the legal field is tough, but their SEO and content team made it happen. We now rank in the top 3 for our most important keywords. Exceptional work.',
    pinned: false,
  },
  {
    id: '16',
    name: 'Olivia King',
    company: 'PetPals Store',
    avatar: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman pet',
    rating: 5,
    quote: 'Their expertise in conversion rate optimization increased our online store\'s revenue by over 30%. They identified and fixed issues we didn\'t even know we had. Invaluable service.',
    pinned: false,
  },
];
