import type { Service } from '@/types/service';

export const initialServices: Service[] = [
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    description: 'A comprehensive suite of digital marketing services designed to elevate your brand and accelerate growth across all digital channels.',
    icon: 'https://placehold.co/128x128.png',
    price: '950.00',
    originalPrice: '1100.00',
    popular: true,
    metaTitle: 'Comprehensive Digital Marketing Services',
    metaDescription: 'Elevate your brand with our full-suite digital marketing services, including SEO, PPC, and content strategy.',
    metaKeywords: 'digital marketing, seo, ppc, content marketing',
    ogImage: 'https://placehold.co/1200x630.png',
  },
  {
    slug: 'social-media-management',
    title: 'Social Media Management',
    description: 'Engage your audience and build a loyal community. We create and manage social media campaigns that resonate with your followers.',
    icon: 'https://placehold.co/128x128.png',
    price: '320.00',
    originalPrice: '355.00',
    popular: false,
    metaTitle: 'Expert Social Media Management Services',
    metaDescription: 'Build a vibrant community and engage your audience with our professional social media management services.',
    metaKeywords: 'social media, community management, content creation',
    ogImage: 'https://placehold.co/1200x630.png',
  },
  {
    slug: 'web-development',
    title: 'Web Development',
    description: 'We build fast, responsive, and user-friendly websites that provide an exceptional user experience and drive conversions.',
    icon: 'https://placehold.co/128x128.png',
    price: '69.00',
    originalPrice: '69.00',
    popular: true,
    metaTitle: 'Professional Web Development Services',
    metaDescription: 'Get a fast, responsive, and user-friendly website designed to convert visitors into customers.',
    metaKeywords: 'web development, responsive design, website creation',
    ogImage: 'https://placehold.co/1200x630.png',
  },
  {
    slug: 'digital-pr',
    title: 'Digital PR (Press Released)',
    description: 'Enhance your brand\'s reputation and reach with strategic digital press releases and media outreach campaigns.',
    icon: 'https://placehold.co/128x128.png',
    price: '450.00',
    originalPrice: '500.00',
    popular: false,
    metaTitle: 'Strategic Digital PR and Press Release Services',
    metaDescription: 'Boost your brand\'s reputation and media presence with our expert Digital PR and press release services.',
    metaKeywords: 'digital pr, press release, media outreach',
    ogImage: 'https://placehold.co/1200x630.png',
  },
];
